spring:
  application:
    name: spring-security

  main: 
      allow-circular-references: true
      

    

    
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cvt
    username: root
    password: Karimax@2023
  
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/staging_cvt_database
#    username: forge
#    password: MuXaMinPLyX0eCYGJKKk
 
 
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    
    

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB
file:
  upload-dir: ./uploads
    
    
logging:
  level:
    root: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: DEBUG
    
    
 
  
